// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PodiumCaseStudy.Data;

namespace PodiumCaseStudy.Migrations
{
    [DbContext(typeof(PodiumDbContext))]
    [Migration("20200909203354_RemoveApplicantIdFromRequirement")]
    partial class RemoveApplicantIdFromRequirement
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PodiumCaseStudy.Data.Entities.Applicant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Applicants");
                });

            modelBuilder.Entity("PodiumCaseStudy.Data.Entities.MortgageProposal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MortgageRequirementId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MortgageRequirementId");

                    b.ToTable("MortgageProposals");
                });

            modelBuilder.Entity("PodiumCaseStudy.Data.Entities.MortgageRequirement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DepositAmount")
                        .HasColumnType("int");

                    b.Property<int>("PropertyValue")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantId");

                    b.ToTable("MortgageRequirements");
                });

            modelBuilder.Entity("PodiumCaseStudy.Data.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("InterestRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Lender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("LoanToValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("LoanType")
                        .HasColumnType("int");

                    b.Property<Guid?>("MortgageProposalId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MortgageProposalId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("PodiumCaseStudy.Data.Entities.MortgageProposal", b =>
                {
                    b.HasOne("PodiumCaseStudy.Data.Entities.MortgageRequirement", "MortgageRequirement")
                        .WithMany()
                        .HasForeignKey("MortgageRequirementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PodiumCaseStudy.Data.Entities.MortgageRequirement", b =>
                {
                    b.HasOne("PodiumCaseStudy.Data.Entities.Applicant", "Applicant")
                        .WithMany()
                        .HasForeignKey("ApplicantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PodiumCaseStudy.Data.Entities.Product", b =>
                {
                    b.HasOne("PodiumCaseStudy.Data.Entities.MortgageProposal", null)
                        .WithMany("Products")
                        .HasForeignKey("MortgageProposalId");
                });
#pragma warning restore 612, 618
        }
    }
}
